server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BugBusters
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka