services:
  - name: APIGateway
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: APIGateway
    dockerContext: .
    dockerfilePath: Dockerfile

  - name: ServiceRegistry 
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    region: oregon
    plan: free
    rootDir: ServiceRegistry      # Correct the path here to match your folder structure
    dockerContext: .              # Use the current directory as the Docker context
    dockerfilePath: Dockerfile    # Specify the Dockerfile path

  - name: PestService
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: PestService
    dockerContext: .
    dockerfilePath: Dockerfile

  - name: UserService
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: UserService
    dockerContext: .
    dockerfilePath: Dockerfile
