services:
  - name: api-gateway
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: APIGateway
    dockerContext: .
    dockerfilePath: Dockerfile

  - name: service-registry
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    region: oregon
    plan: free
    rootDir: ServiceRegistry      # Correct the path here to match your folder structure
    dockerContext: .              # Use the current directory as the Docker context
    dockerfilePath: Dockerfile    # Specify the Dockerfile path


  - name: face-service
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: face-service
    dockerContext: .
    dockerfilePath: Dockerfile

  - name: pest-service
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: PestService
    dockerContext: .
    dockerfilePath: Dockerfile

  - name: user-service
    type: web
    repo: https://github.com/Surajhub21/IdeaLab
    env: docker
    plan: free
    region: oregon
    rootDir: UserService
    dockerContext: .
    dockerfilePath: Dockerfile
